// Code generated by MockGen. DO NOT EDIT.
// Source: ap_collection_repo.go

// Package mock_apcollectionrepo is a generated GoMock package.
package mock_apcollectionrepo

import (
	context "context"
	reflect "reflect"

	rssiv1 "github.com/ZecretBone/ips-rssi-service/internal/gen/proto/ips/rssi/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// InsertOne mocks base method.
func (m *MockRepository) InsertOne(ctx context.Context, request *rssiv1.RegisterApRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOne", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockRepositoryMockRecorder) InsertOne(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockRepository)(nil).InsertOne), ctx, request)
}

// IsExpectedApExisted mocks base method.
func (m *MockRepository) IsExpectedApExisted(ctx context.Context, request *rssiv1.GetCoordinateRequest) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExpectedApExisted", ctx, request)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExpectedApExisted indicates an expected call of IsExpectedApExisted.
func (mr *MockRepositoryMockRecorder) IsExpectedApExisted(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExpectedApExisted", reflect.TypeOf((*MockRepository)(nil).IsExpectedApExisted), ctx, request)
}
